### ISSUE TITLE
Undefined property: stdClass::$Hostnames  

### ISSUE THREAD

**Issue by Jivings** [ghostzero/bunny-action#2]
Build is failing with the error:

```
In FileCompare.php line 141:
                                            
  Undefined property: stdClass::$Hostnames  
```

My config:

```
-  name: 🐰 Deploy to Bunny
    uses: own3d/bunny-action@main
    env:
      BUNNY_API_ACCESS_KEY: ${{ secrets.BUNNY_API_ACCESS_KEY }}
      BUNNY_STORAGE_USERNAME: ${{ secrets.BUNNY_STORAGE_USERNAME }}
      BUNNY_STORAGE_PASSWORD: ${{ secrets.BUNNY_STORAGE_PASSWORD }}
      BUNNY_PULL_ZONE_ID: ${{ secrets.BUNNY_ZONE_ID }}
    with:
      args: deploy --dir=public
```
